/**
 * Created by shilim on 2017/7/10.
 */
export const CHANGE_PAGE_NUM = 'CHANGE_EQUIPMENT_TYPE_PAGE_NUM';
export const GET_EQUIPMENT_TYPE_LIST = 'GET_EQUIPMENT_TYPE_LIST';
export const SAVE_EQUIPMENT_TYPE_LIST = 'SAVE_EQUIPMENT_TYPE_LIST';
export const ADD_EQUIPMENT_TYPE = 'ADD_EQUIPMENT_TYPE';
