/**
 * Created by shilim on 2017/7/10.
 */
export const CHANGE_PAGE_NUM = 'CHANGE_EQUIPMENT_LOAN_LOAN_PAGE_NUM';
export const GET_EQUIPMENT_LOAN_LIST = 'GET_EQUIPMENT_LOAN_LIST';
export const SAVE_EQUIPMENT_LOAN_LIST = 'SAVE_EQUIPMENT_LOAN_LIST';
export const GET_ONE_EQUIPMENT_LOAN = 'GET_ONE_EQUIPMENT_LOAN';
