/**
 * Created by shilim on 2017/7/10.
 */
export const CHANGE_PAGE_NUM = 'CHANGE_PLACE_LEASE_RECORD_PAGE_NUM';
export const GET_PLACE_LEASE_RECORD_LIST = 'GET_PLACE_LEASE_RECORD_LIST';
export const SAVE_PLACE_LEASE_RECORD_LIST = 'SAVE_PLACE_LEASE_RECORD_LIST';
export const GET_ONE_PLACE_LEASE_RECORD = 'GET_ONE_PLACE_LEASE_RECORD';
